# Generated by Django 4.1.6 on 2023-02-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='user_type',
            field=models.PositiveIntegerField(choices=[('', '-------'), (0, 'is_admin'), (1, 'is_office')]),
        ),
    ]
