# Generated by Django 4.1.6 on 2023-02-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_tblofficeuser_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblofficeuser',
            old_name='url_addres',
            new_name='url_address',
        ),
    ]
