# Generated by Django 4.1.6 on 2023-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_url_addres_tblofficeuser_url_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblofficeuser',
            name='url_address',
            field=models.CharField(max_length=200),
        ),
    ]
