# Generated by Django 4.1.6 on 2023-02-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_tblofficeuser_url_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblofficeuser',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
