# Generated by Django 4.1.6 on 2023-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_tblofficeuser_url_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblofficeuser',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tblofficeuser',
            name='url_address',
            field=models.CharField(max_length=200),
        ),
    ]
