# Generated by Django 4.1.6 on 2023-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_tblofficeuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblofficeuser',
            name='city',
            field=models.PositiveIntegerField(choices=[('', '-------'), (1, 'البيضاء'), (2, 'بنغازي')], default=1),
        ),
    ]
