# Generated by Django 4.1.6 on 2023-02-08 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_tbluser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office', to='account.tblofficeuser')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000000000.0)])),
                ('sender_commission', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000000.0)])),
                ('recipient_commission', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000000.0)])),
                ('commission_from_sender', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000.0)])),
                ('commission_from_recipient', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000.0)])),
                ('approval_by_recipient', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('approval_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=250, null=True)),
                ('recipient_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_office', to='account.tblofficeuser')),
                ('sender_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_office', to='account.tblofficeuser')),
            ],
        ),
    ]
