# Generated by Django 4.1.6 on 2023-02-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficePhone',
        ),
    ]
