# Generated by Django 4.1.6 on 2023-02-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_tbluser_user_type'),
        ('office', '0003_officephone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoneyTransfer',
            new_name='TblMoneyTransfer',
        ),
        migrations.RenameModel(
            old_name='OfficePhone',
            new_name='TblOfficePhone',
        ),
    ]
