# Generated by Django 4.1.6 on 2023-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_tblmoneytransfer_rejection_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmoneytransfer',
            name='rejection',
            field=models.BooleanField(default=False),
        ),
    ]
