# Generated by Django 4.1.6 on 2023-02-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_tblmoneytransfer_rejection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblmoneytransfer',
            old_name='approval_at',
            new_name='update_at',
        ),
    ]
