# Generated by Django 4.1.6 on 2023-02-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_rename_approval_at_tblmoneytransfer_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblmoneytransfer',
            old_name='update_at',
            new_name='approval_at',
        ),
        migrations.AddField(
            model_name='tblmoneytransfer',
            name='rejection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
