# Generated by Django 4.1.6 on 2023-02-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_rename_update_at_tblmoneytransfer_approval_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblmoneytransfer',
            old_name='rejection_note',
            new_name='note2',
        ),
    ]
